# Generated by Django 4.2 on 2023-04-27 21:37

from typing import List

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies: List = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('sqlite', 'Sqlite'), ('postgresql', 'Postgresql'), ('elasticsearch', 'Elasticsearch')], max_length=50)),
                ('uri', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=50)),
                ('from_table', models.CharField(max_length=255)),
                ('to_table', models.CharField(max_length=255)),
                ('index_col', models.CharField(default='id', max_length=255)),
                ('sync', models.BooleanField(default=False)),
                ('time_interval', models.CharField(choices=[('1 min', 'One Min'), ('5 mins', 'Five Mins'), ('1 hour', 'One Hour')], default='1 min', max_length=50)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.model')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='app.database')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='app.database')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name_plural': 'Processes',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_name', models.CharField(max_length=50)),
                ('table', models.CharField(max_length=50)),
                ('through_table', models.CharField(max_length=50)),
                ('suffix', models.CharField(default='_id', max_length=50)),
                ('flat', models.BooleanField(default=False)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='app.model')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='app.process')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('str', 'Str'), ('int', 'Int'), ('float', 'Float'), ('date', 'Date'), ('datetime', 'Datetime'), ('UUID', 'Uuid')], max_length=50)),
                ('default', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='app.model')),
            ],
        ),
    ]
